import { execSync } from 'child_process';
import * as dotenv from 'dotenv';

dotenv.config();

const GH_PATH = '"C:\\Program Files\\GitHub CLI\\gh.exe"';
const REPO = 'nashy3k/autism-comm-cards';
const TITLE = '[Shadow PR] Momentum: Project Status Badge';
const BODY = `Momentum has detected this repository is stagnant (last active > 3 days ago).

## Proposed Improvement
Add a **Momentum Status Badge** to the README to signal active recovery.

### Code Change for \`README.md\`
\`\`\`markdown
## 🚀 Project Status

![Momentum Badge](https://img.shields.io/badge/Status-Accelerated_by_Momentum-blueviolet)

This project was checked by **Momentum: The Shadow Developer**.
\`\`\`

---
*Generated by Momentum Agent*`;

try {
    console.log(`Targeting repo: ${REPO}`);
    const cmd = `${GH_PATH} issue create -R ${REPO} --title "${TITLE}" --body "${BODY}"`;
    const output = execSync(cmd, { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] });
    console.log(`Success! URL: ${output.trim()}`);
} catch (error: any) {
    console.error('FAILED');
    console.error(error.message);
}
